apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-kubevirt-csi-driver
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    namespace: kubevirt-csi-driver
    name: infra-cluster-credentials
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: KubevirtProviderSpec